name: ai-lab-notebook
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - dataclasses-json==0.6.7
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - fastapi==0.123.3
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==0.2.43
      - langchain-ollama==0.1.1
      - langchain-text-splitters==0.0.2
      - langgraph==1.0.4
      - langgraph-sdk==0.2.10
      - langsmith==0.1.147
      - marshmallow==3.26.1
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - ollama==0.6.1
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==23.2
      - platformdirs==4.5.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.46.0
      - smmap==5.0.2
      - sqlalchemy==2.0.44
      - starlette==0.50.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.23.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /Users/payalsaha/miniconda3/envs/ai-lab-notebook
